import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { BsArrowLeftCircle, BsFillMoonFill, BsFillSunFill, BsFullscreenExit, BsThreeDots } from "react-icons/bs";
import { useDispatch, useSelector } from "react-redux";
import { getLang, isDark } from "../store/selector";
import { HU, GB } from 'country-flag-icons/react/3x2'
import png1 from "../public/kartografusok/1.png"
import png2 from "../public/kartografusok/2.png"
import png3 from "../public/kartografusok/3.png"
import png4 from "../public/kartografusok/4.png"
import png5 from "../public/kartografusok/5.png"
import png6 from "../public/kartografusok/6.png"
import png7 from "../public/kartografusok/7.png"
import png8 from "../public/kartografusok/8.png"
import png9 from "../public/kartografusok/9.png"
import png10 from "../public/kartografusok/10.png"
import png11 from "../public/kartografusok/11.png"
import png12 from "../public/kartografusok/12.png"
import png13 from "../public/kartografusok/13.png"
import png14 from "../public/kartografusok/14.png"
import png15 from "../public/kartografusok/15.png"
import png16 from "../public/kartografusok/16.png"
import png17 from "../public/kartografusok/17.png"
import png18 from "../public/kartografusok/18.png"
import png19 from "../public/kartografusok/19.png"
import png20 from "../public/kartografusok/20.png"
import png21 from "../public/kartografusok/21.png"
import Image from "next/image"

export default function Kartografusok() {
    const darkMode = useSelector(isDark);
    const lang = useSelector(getLang);
    const dispatch = useDispatch();

    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>HP - Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='dark:bg-gradient-to-b dark:from-gray-800 dark:to-gray-500 px-10 md:px-20 lg:px-30 bg-gradient-to-b from-gray-300 to-gray-100'>
                <section className='min-h-screen'>
                    <nav className='py-10 mb-8 flex justify-between'>
                        <div className='flex gap-10'>
                            <Link href="/">
                                <BsArrowLeftCircle className='cursor-pointer text-2xl lg:text-3xl dark:text-white text-gray-800' />
                            </Link>
                            <h1 className='text-lg md:text-xl lg:text-2xl dark:text-white font-burtons text-gray-800'>kartográfusok</h1>
                        </div>
                        <ul className='flex items-center'>
                            <li>
                                {darkMode ?
                                    <BsFillSunFill onClick={() => {
                                        dispatch({ type: "CHANGE_DARKNESS" })
                                    }} className='cursor-pointer text-2xl lg:text-3xl text-white' />
                                    :
                                    <BsFillMoonFill onClick={() => {
                                        dispatch({ type: "CHANGE_DARKNESS" })
                                    }} className='cursor-pointer text-2xl lg:text-3xl text-gray-800' />
                                }
                            </li>
                            <li>
                                {lang === "ENG" ?
                                    <HU title='Váltás magyarra' className='h-7 ml-8 cursor-pointer border-2 border-black' onClick={() => dispatch({ type: "CHANGE_LANGUAGE" })} />
                                    :
                                    <GB title='Change to english' className='h-7 ml-8 cursor-pointer border-2 border-black' onClick={() => dispatch({ type: "CHANGE_LANGUAGE" })} />
                                }
                            </li>
                        </ul>
                    </nav>

                    {/* <div className="flex mb-10 w-9/12 center mx-auto gap-10">
                        <div className="w-2/3 bg-gray-500 h-60 rounded-3xl"></div>
                        <div className="w-1/3 bg-gray-400 h-60 rounded-3xl"></div>
                    </div>
                    <div className="flex mb-4 w-9/12 center mx-auto gap-10">
                        <div className="w-1/2 bg-gray-500 h-96 rounded-3xl"></div>
                        <div className="w-1/2 h-96 rounded-3xl flex gap-10">
                            <div className="w-1/2 bg-gray-500 h-60 rounded-3xl"></div>
                            <div className="w-1/2 bg-gray-400 h-60 rounded-3xl"></div>
                        </div>
                    </div> */}

                    {/* <div className="grid grid-cols-8 gap-4">
                        <div className="bg-blue-300 col-span-6 row-span-2">a</div>
                        <div className="bg-red-300 col-span-2 row-span-2"></div>
                        <div className="bg-green-300 col-span-4 row-span-4"></div>
                        <div className="bg-yellow-300 row-span-2"></div>
                    </div> */}

                    {/* grid-flow-row-dense */}

                    <div className="grid grid-cols-8 grid-rows-1 h-min pb-10 center mx-auto gap-10 lg:w-9/12 w-11/12 center">
                        <div className="lg:col-span-5 col-span-8 dark:bg-orange-50 bg-sky-600 rounded-3xl p-10 flex flex-col justify-center shadow-card">
                            <h3 className="text-2xl md:text-2xl mb-5 lg:text-4xl text-gray-800 font-burtons">Kartográfusok</h3>
                            <p className="text-lg md:text-lg lg:text-xl">{lang === "ENG" ? <p>I made this as my university thesis. Three program components work together to make this application work; backend that I wrote in NestJs, my frontend which is ReactJs, and SocketIO.</p> : <p>Ezt a projektet az egyetemen, szakmai dolgozatként csináltam. Az alkalmazás három részre oszlik, front-enden ReactJs működik, back-enden NestJs, a kapcsolatért pedig SocketIO felel. A grafikai elemeket (kártyák, térkép) nem én hoztam létre, viszont minden más a saját munkám.</p>}</p>
                        </div>
                        <div className="lg:col-span-3 col-span-8 dark:bg-orange-100 bg-sky-700 rounded-3xl flex flex-col justify-between p-5 shadow-card">
                            <div><BsThreeDots className="text-4xl" /></div>
                            <div className=""></div>
                            <div className="font-burtons text-2xl">{lang === "ENG" ? <p>Documentation</p> : <p>Dokumentáció</p>}</div>
                        </div>
                    </div>


                    <div className="grid grid-cols-8 auto-rows-[300px] grid-flow-dense pb-10 mx-auto gap-10 lg:w-9/12 w-11/12 center content-between">

                        {/* ELSŐ */}
                        <div className="2xl:col-span-4 xl:col-span-4 col-span-8 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png1} className="object-cover h-full " />
                        </div>

                        <div className="2xl:col-span-4 xl:col-span-4 col-span-8 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png17} className="object-cover h-full " />
                        </div>

                        {/* MÁSODIK */}
                        <div className="2xl:col-span-3 xl:col-span-3 lg:col-span-4 md:col-span-4 sm:col-span-4 col-span-8 row-span-1 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png2} className="object-cover h-full w-full object-top" />
                        </div>

                        <div className="2xl:col-span-2 xl:col-span-3 lg:col-span-4 md:col-span-4 sm:col-span-4 col-span-8 dark:bg-orange-200 bg-sky-700 rounded-3xl flex flex-col justify-center p-5 shadow-card">
                            <div className="2xl:text-lg italic">{lang === "ENG" ? <p>Unfortunatelly, I can't host the game since I don't have the rights for that. The pictures show the content of the game. Some of my other projects, that are my own idea can be and are hosted.</p> : <p>Sajnos a játékot nem oszthatom meg, mert a szerzői jog a kiadót illeti, viszont itt van néhány kép a játékból. A többi projektemet, ami a saját ötletem volt, azokat megosztottam.</p>}</div>
                        </div>

                        <div className="2xl:col-span-3 xl:col-span-2 lg:col-span-4 sm:col-span-4 col-span-8 row-span-1 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png19} className="h-full w-full object-cover" />
                        </div>

                        {/* HARMADIK */}
                        <div className="2xl:col-span-4 xl:col-span-3 xl:col-start-2 col-start-1 col-span-8 row-span-1 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png14} className="h-full w-full object-cover" />
                        </div>

                        <div className="2xl:col-span-2 xl:col-span-3 lg:col-span-4 sm:col-span-4 col-span-8 dark:bg-orange-300 bg-sky-700 rounded-3xl flex flex-col justify-center p-5 shadow-card">
                            <div className="2xl:text-lg lg:text-xl italic">
                                {lang === "ENG" ? <p>The site can be used even as a guest, but there is also a registration option. I included this feature so that players can compete on the leaderboard.</p> : <p>Az oldalt lehet használni vendégként, de van regisztrációs lehetőség is. Ezt azért vittem bele, hogy a játékosok versenyezni tudjanak a ranglétrán.</p>}</div>
                        </div>

                        <div className="2xl:col-span-2 xl:col-span-3 lg:col-span-4 xl:col-start-2 sm:col-span-4 col-start-1 col-span-8 row-span-1 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png4} className="h-full w-full object-cover" />
                        </div>



                        {/* NEGYEDIK */}
                        <div className="2xl:col-span-2 xl:col-span-3 lg:col-span-4 sm:col-span-4 col-span-8 dark:bg-orange-300 bg-sky-700 rounded-3xl flex flex-col justify-center p-5 shadow-card">
                            <div className="2xl:text-lg lg:text-xl italic">
                                {lang === "ENG" ? <p>There is an administration panel available, where all player data can be modified, and new levels and certain game cards can be created and deleted.</p> : <p>Van egy adminisztrációs panel is, ahol módosítani lehet az összes játékos adatait, ezenkívül lehet létrehozni és törölni új pályákat, illetve bizonyos, játékban szereplő kártyákat is.</p>}</div>
                        </div>

                        <div className="2xl:col-span-4 xl:col-span-4 col-span-8 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png5} className="object-cover h-full " />
                        </div>

                        <div className="2xl:col-span-2 xl:col-span-4 lg:col-span-4 col-span-8 row-span-1 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png8} className="h-full w-full object-cover" />
                        </div>

                        {/* ÖTÖDIK */}
                        <div className="2xl:col-span-4 xl:col-span-4 col-span-8 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png7} className="object-cover h-full " />
                        </div>

                        <div className="2xl:col-span-4 xl:col-span-4 col-span-8 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png9} className="object-cover h-full " />
                        </div>

                        {/* HATODIK */}
                        <div className="2xl:col-span-2 xl:col-span-3 lg:col-span-4 col-span-8 row-span-1 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png10} className="h-full w-full object-cover" />
                        </div>

                        <div className="2xl:col-span-2 xl:col-span-5 col-span-8 row-span-1 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png3} className="h-full w-full object-cover" />
                        </div>

                        <div className="2xl:col-span-4 xl:col-span-4 col-span-8 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png6} className="object-cover h-full " />
                        </div>

                        {/* HETEDIK */}
                        <div className="2xl:col-span-4 xl:col-span-4 col-span-8 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png11} className="object-cover h-full " />
                        </div>

                        <div className="2xl:col-span-4 xl:col-span-5 col-span-8 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png12} className="object-cover h-full " />
                        </div>

                        {/* NYOLCAS */}
                        <div className="2xl:col-span-2 xl:col-span-3 sm:col-span-4 col-span-8 row-span-1 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png13} className="h-full w-full object-cover" />
                        </div>

                        <div className="2xl:col-span-4 xl:col-span-5 col-span-8 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png15} className="object-cover h-full " />
                        </div>

                        <div className="2xl:col-span-2 xl:col-span-3 lg:col-span-4 sm:col-span-4 col-span-8 dark:bg-orange-300 bg-sky-700 rounded-3xl flex flex-col justify-center p-5 shadow-card">
                            <div className="2xl:text-lg lg:text-xl italic">
                                {lang === "ENG" ? "" : <p>Ha játszani szeretnénk a barátainkkal, akkor egy szoba létrehozása után a szobakódra lesz szükségük. Ezt a socketIO generálja. A kód beírásával csatlakozhatnak a szobánkba. Itt lehet chatelni.</p>}</div>
                        </div>

                        {/* KILENCES */}
                        <div className="2xl:col-span-4 xl:col-span-4  col-span-8 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png16} className="object-cover h-full " />
                        </div>

                        <div className="2xl:col-span-4 xl:col-span-4  col-span-8 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png17} className="object-cover h-full " />
                        </div>

                        {/* TIZES */}
                        <div className="2xl:col-span-3 xl:col-span-2 lg:col-span-4 sm:col-span-4 col-span-8 2xl:row-span-2 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png19} className="h-full w-full object-cover" />
                        </div>

                        <div className="2xl:col-span-3 xl:col-span-3 lg:col-span-4 sm:col-span-4 col-span-8 row-span-1 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png18} className="h-full w-full object-cover lg:object-left xl:object-center sm:object-left object-center" />
                        </div>

                        <div className="2xl:col-span-2 xl:col-span-3 lg:col-span-4 sm:col-span-4 col-span-8 dark:bg-orange-300 bg-sky-700 rounded-3xl flex flex-col justify-center p-5 shadow-card">
                            <div className="2xl:text-lg lg:text-xl italic">
                                {lang === "ENG" ? "" : <p>Amint a játék elindult, továbbra is lehet chatelni. Rajzolni kell, tetrisezni és építgetni. Ne felejtsük el, hogy kicsit kiszúrni sem ítélendő az ellenfeleinkkel.</p>}</div>
                        </div>

                        <div className="2xl:col-span-5 xl:col-span-3 col-span-8 row-span-1 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png21} className="object-cover h-full xl:object-left object-center" />
                        </div>

                        {/* TIZENEGYES */}

                        <div className="2xl:col-span-2 xl:col-span-2 lg:col-span-4 sm:col-span-4 col-span-8 row-span-1 relative rounded-3xl overflow-hidden">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png20} className="h-full w-full object-cover" />
                        </div>

                        <div className="2xl:col-span-2 xl:col-span-3 lg:col-span-4 col-span-8 dark:bg-orange-300 bg-sky-700 rounded-3xl flex flex-col justify-center p-5 shadow-card">
                            <div className="2xl:text-lg lg:text-xl italic text-center">
                                {lang === "ENG" ? <p>Publisher:</p> : <p>Kiadó:</p>}
                                <p>Thunderwork Games</p>
                                <br />
                                <p>Designer:</p>
                                <p>Jordy Adan</p>
                            </div>

                        </div>

                        {/* <div className="md:col-span-2 col-span-8 dark:bg-orange-300 bg-sky-700 rounded-3xl flex flex-col justify-center p-5 shadow-card">
                            <div className="text-lg md:text-lg lg:text-xl italic">
                                {lang==="ENG"?"":""}</div>
                        </div> */}
                    </div>
                </section>

            </main>
        </div>
    )
}