import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { BsArrowLeftCircle, BsFillMoonFill, BsFillSunFill } from "react-icons/bs";
import { useDispatch, useSelector } from "react-redux";
import { getLang, isDark } from "../store/selector";
import { HU, GB } from 'country-flag-icons/react/3x2'
import png1 from "../public/kartografusok/1.png"
import png2 from "../public/kartografusok/2.png"
import png3 from "../public/kartografusok/3.png"
import png4 from "../public/kartografusok/4.png"
import png5 from "../public/kartografusok/5.png"
import png6 from "../public/kartografusok/6.png"
import png14 from "../public/kartografusok/14.png"
import png21 from "../public/kartografusok/21.png"
import png17 from "../public/kartografusok/17.png"
import png19 from "../public/kartografusok/19.png"
import Image from "next/image"

export default function Kartografusok() {
    const darkMode = useSelector(isDark);
    const lang = useSelector(getLang);
    const dispatch = useDispatch();

    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>HP - Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='dark:bg-gradient-to-b dark:from-gray-800 dark:to-gray-500 px-10 md:px-20 lg:px-30 bg-gradient-to-b from-gray-300 to-gray-100'>
                <section className='min-h-screen'>
                    <nav className='py-10 mb-8 flex justify-between'>
                        <div className='flex gap-10'>
                            <Link href="/">
                                <BsArrowLeftCircle className='cursor-pointer text-2xl lg:text-3xl dark:text-white text-gray-800' />
                            </Link>
                            <h1 className='text-lg md:text-xl lg:text-2xl dark:text-white font-burtons text-gray-800'>kartográfusok</h1>
                        </div>
                        <ul className='flex items-center'>
                            <li>
                                {darkMode ?
                                    <BsFillSunFill onClick={() => {
                                        dispatch({ type: "CHANGE_DARKNESS" })
                                    }} className='cursor-pointer text-2xl lg:text-3xl text-white' />
                                    :
                                    <BsFillMoonFill onClick={() => {
                                        dispatch({ type: "CHANGE_DARKNESS" })
                                    }} className='cursor-pointer text-2xl lg:text-3xl text-gray-800' />
                                }
                            </li>
                            <li>
                                {lang === "ENG" ?
                                    <HU title='Váltás magyarra' className='h-7 ml-8 cursor-pointer border-2 border-black' onClick={() => dispatch({ type: "CHANGE_LANGUAGE" })} />
                                    :
                                    <GB title='Change to english' className='h-7 ml-8 cursor-pointer border-2 border-black' onClick={() => dispatch({ type: "CHANGE_LANGUAGE" })} />
                                }
                            </li>
                        </ul>
                    </nav>

                    {/* <div className="flex mb-10 w-9/12 center mx-auto gap-10">
                        <div className="w-2/3 bg-gray-500 h-60 rounded-3xl"></div>
                        <div className="w-1/3 bg-gray-400 h-60 rounded-3xl"></div>
                    </div>
                    <div className="flex mb-4 w-9/12 center mx-auto gap-10">
                        <div className="w-1/2 bg-gray-500 h-96 rounded-3xl"></div>
                        <div className="w-1/2 h-96 rounded-3xl flex gap-10">
                            <div className="w-1/2 bg-gray-500 h-60 rounded-3xl"></div>
                            <div className="w-1/2 bg-gray-400 h-60 rounded-3xl"></div>
                        </div>
                    </div> */}

                    {/* <div className="grid grid-cols-8 gap-4">
                        <div className="bg-blue-300 col-span-6 row-span-2">a</div>
                        <div className="bg-red-300 col-span-2 row-span-2"></div>
                        <div className="bg-green-300 col-span-4 row-span-4"></div>
                        <div className="bg-yellow-300 row-span-2"></div>
                    </div> */}

                    <div className="grid grid-cols-8 pb-10 center mx-auto gap-10 w-9/12 grid-flow-row-dense center">

                        <div className="md:col-span-5 col-span-8 dark:bg-orange-50  bg-sky-600 rounded-3xl p-10">
                            <h3 className="text-2xl md:text-2xl mb-5 lg:text-4xl text-gray-800 font-burtons">Kartográfusok</h3>
                            <p className="text-lg md:text-lg lg:text-xl">I made this as my university thesis. Three program components work together to make this application work; backend that I wrote in
                                NestJs, my frontend which is ReactJs, and SocketIO.</p>
                        </div>
                        <div className="md:col-span-3 col-span-8 dark:bg-orange-100 bg-sky-700 rounded-3xl">asdasd</div>

                        {/* ELSŐ SOR */}
                        <div className="xl:col-span-4 col-span-8 dark:bg-orange-100 bg-sky-700 rounded-3xl overflow-hidden relative">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png1} className="object-cover h-full" />
                        </div>

                        <div className="xl:col-span-4 col-span-8 dark:bg-orange-100 bg-sky-700 rounded-3xl overflow-hidden relative">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png17} className="object-cover h-full" />
                        </div>

                        
                        {/* MÁSODIK SOR */}
                        <div className="xl:col-span-2 sm:col-span-4 col-span-8 row-span-1 dark:bg-orange-200 bg-sky-800 rounded-3xl overflow-hidden relative">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png2} className="object-cover h-full md:w-full" />
                        </div>

                        <div className="xl:col-span-3 sm:col-span-4 col-span-8 row-span-2 dark:bg-orange-200 bg-sky-800 rounded-3xl overflow-hidden relative">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png19} className="object-cover md:w-full h-full " />
                        </div>

                        {/* <div className="xl:col-span-3 sm:col-span-4 col-span-8 row-span-2 dark:bg-orange-200 bg-sky-800 rounded-3xl overflow-hidden relative">
                            <div className="absolute h-full w-full shadow-innerShadow shadow-black"></div>
                            <Image src={png14} className="object-cover md:h-full w-full" />
                        </div> */}


                        {/* <div className="dark:bg-orange-300 bg-sky-900 rounded-3xl">a</div>
                        <div className="dark:bg-orange-300 bg-sky-900 rounded-3xl">a</div>
                        <div className="dark:bg-orange-200 bg-sky-800 rounded-3xl">a</div>
                        <div className="dark:bg-orange-200 bg-sky-800 rounded-3xl">a</div>
                        <div className="dark:bg-orange-200 bg-sky-800 rounded-3xl">a</div>
                        <div className="dark:bg-orange-200 bg-sky-800 rounded-3xl">a</div> */}

                    </div>
                </section>

            </main>
        </div>
    )
}